CREATE DATABASE onimisea;

CREATE TABLE admins (
  id BIGSERIAL NOT NULL PRIMARY KEY,
  username VARCHAR(50) NOT NULL,
  email VARCHAR(50) NOT NULL,
  phone BIGINT NOT NULL,
  password VARCHAR(1000) NOT NULL,
  role VARCHAR(15) NOT NULL 
);